version: '3.8'

services:
  news_admin:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: news_project.settings

  news_user:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: news_project.settings

  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  static_volume:
